### ISSUE TITLE
need a delete verb

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-easybake#30]
It's fairly easy to add attributes, and classes to an existing node:

``` css
div .myclass {
    class: attr('class') newclass; /* adds newclass to existing set of classes */
    attr-haha: thisone; /* adds new attribute named haha */
    data-foo-type: 'my data type'; /* adds new attribute data-foo-type */
}
```

But there is no simple way to either remove an existing attribute, nor delete one class from a list of classes.

perhaps:

``` css
div .myclass {
   class: remove(myclass) newclass; /* replaces myclass with newclass, leaves other classes */
   attr-haha: remove();
}
```
