### ISSUE TITLE
selectors under an element:deferred evaluated in a strange order

### ISSUE THREAD

**Issue by aiwenar** [openstax/cnx-easybake#80]
Assuming a single `parent` with two `child`ren, evaluation order will be as follows:

1. `parent`
2. `parent > child:nth-child(0)`
3. `parent > child:nth-child(0):deferred`
4. `parent:deferred > child:nth-child(0)`
5. `parent:deferred > child:nth-child(0):deferred`
6. `parent > child:nth-child(1)`
7. `parent > child:nth-child(1):deferred`
8. `parent:deferred > child:nth-child(1)`
9. `parent:deferred > child:nth-child(1):deferred`
10. `parent:deferred`

I'm guessing that `:deferred`, unless it's the last selector, will only increase specificity, making rule fire later, but will not otherwise affect execution order.

A slightly more complex example:

**HTML**
```xhtml
<root>
<a>
    <b>
        <c/>
    </b>
    <d/>
</a>
</root>
```

**CSS**
```css
root { counter-reset: test 0; }

root {
    counter-increment: test;
    attr-before: counter(test);
}
root:deferred {
    counter-increment: test;
    attr-after: counter(test);
}

root * {
    counter-increment: test;
    attr-before: counter(test);
}
root *:deferred {
    counter-increment: test;
    attr-after: counter(test);
}
root:deferred * {
    counter-increment: test;
    attr-post-before: counter(test);
}
root:deferred *:deferred {
    counter-increment: test;
    attr-post-after: counter(test);
}
```

**Expected output**
```xhtml
<root before="1" after="18">
<a before="2" after="9" post-before="9" post-after="17">
    <b before="3" after="6" post-before="11" post-after="14">
        <c before="4" after="5" post-before="12" post-after="13"/>
    </b>
    <d before="7" after="8" post-before="15" post-after="16"/>
</a>
</root>
```
1. `root` is processed first
2. then `root`s children, in DFS order, with child's `:deferred` being evaluated after grandchildren
3. then again `roots` children in DFS order, this time matching only rules rooted at `root:deferred`
4. then `root`s `:deferred`

**Actual output**
```xhtml
<root before="1" after="18">
  <a before="2" after="15" post-before="16" post-after="17">
    <b before="3" after="8" post-before="9" post-after="10">
      <c before="4" after="5" post-before="6" post-after="7"/>
    </b>
    <d before="11" after="12" post-before="13" post-after="14"/>
  </a>
</root>
```
1. `root` is processed first
2. then `root`s children, in DFS order, with child's `:deferred` being evaluated after grandchildren, except `root:deferred > child` is evaluated immediately after `child:deferred`
3. then `root:deferred` is finally evaluated
